### ISSUE TITLE
russian characters ?

### ISSUE THREAD

**Issue by imKota** [MZSHproject/YU-RIS-PATCH#1]
Hello, @MZSHproject 
Could you add support for Russian characters?

**Comment by MZSHproject** [comment]
> Hello, @MZSHproject
> Could you add support for Russian characters?

For Russian, change lfCharSet and lfFaceName in CreateFontIndirectA to Russian, and change characters check table in exe.
To find characters check table, you can find it in TextOutA.

**Comment by imKota** [comment]
@MZSHproject Could you tell us more about the "characters check table"?

**Comment by MZSHproject** [comment]
> @MZSHproject Could you tell us more about the "characters check table"?

In exe. you can find a table like this:
`0019b540h: 00 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ; ................
0019b550h: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ; ................
0019b560h: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; ................
0019b570h: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; ................
0019b580h: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; ................
0019b590h: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ; ................
0019b5a0h: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ; ................
0019b5b0h: 01 01 01 01 01 01 01 01 01 01 01 01 01 00 00 00 ; ................`
This is characters check table. 
We can see it like this: 
19b541-19b55F: 0x81-0x9F
19b5a0-19b5bc: 0xE0-0xFC
This is range od SJIS characters. You should change it to Russian.
eg: In Chinese, it will be changed like this:
`0019b540h: 00 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ; ................
0019b550h: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ; ................
0019b560h: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ; ................
0019b570h: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ; ................
0019b580h: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ; ................
0019b590h: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ; ................
0019b5a0h: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ; ................
0019b5b0h: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 00 ; ................`

**Comment by imKota** [comment]
@MZSHproject Yes, I found a table.
![image](https://user-images.githubusercontent.com/24241471/74601795-f9965080-50b2-11ea-8d6f-b3895c4a2445.png)

But.. What if I don’t know how to change characters range for russian?

**Comment by imKota** [comment]
@MZSHproject can you help? please T_T

**Comment by MZSHproject** [comment]
> @MZSHproject can you help? please T_T
So what's the problem now?
By away, pls tell me what's game's name because different game maybe use different types.
Likes Whirlpool. after 2016, their scripts are not ybn file.
About char table, if you will use double-char, you may change it.
If you want to know more about char table, I think debuging by yourself is the best way.

**Comment by MZSHproject** [comment]
> @MZSHproject can you help? please T_T


[dllmain.zip](https://github.com/MZSHproject/YU-RIS-PATCH/files/4275659/dllmain.zip)
If you have no idea, This code maybe help you.
Try to map the chars.
About map: [https://github.com/jszhtian/Fragment/tree/master/ToHeart2_ScriptEngine](url)

**Comment by imKota** [comment]
> By away, pls tell me what's game's name because different game maybe use different types.

https://vndb.org/v20433  En/Ch releases 2017
scripts not in ybn files and loaded from **scenario** folder

![image](https://user-images.githubusercontent.com/24241471/75691193-03c06d80-5cb5-11ea-9e3b-bdf1d5773acc.png)

**Comment by imKota** [comment]
@MZSHproject in japanese version
![image](https://user-images.githubusercontent.com/24241471/75695191-c1019400-5cba-11ea-9f36-7d7480178a05.png)

with 
> [dllmain.zip](https://github.com/MZSHproject/YU-RIS-PATCH/files/4275659/dllmain.zip)

**Comment by MZSHproject** [comment]
> @MZSHproject in japanese version
> ![image](https://user-images.githubusercontent.com/24241471/75695191-c1019400-5cba-11ea-9f36-7d7480178a05.png)
> 
> with
> 
> > [dllmain.zip](https://github.com/MZSHproject/YU-RIS-PATCH/files/4275659/dllmain.zip)

`
uint16_t SjisUnicodeTable[65536];
void init_fnt_table()
{
	auto fs = fopen("CHS.TBL", "rb");//MAP TABLE. MADE BY YOURSELF
	if (!fs)
	{
		MessageBox(0, L"Can't Find AymTextOut Suppost List File.", L"Aym", 0);
		return;
	}
	fread(SjisUnicodeTable, 1, 65536 * 2, fs);
	fclose(fs);
}

PVOID g_pOldTextOutA = NULL;
typedef int(WINAPI* PfuncTextOutA)(HDC hdc, int x, int y, LPCSTR lpString, int c);
int WINAPI NewTextOutA(HDC hdc, int x, int y, LPCSTR lpString, int c)
{
	unsigned short uChar = 0;
	memcpy((unsigned char*)&uChar + 1, lpString, 1);
	memcpy((unsigned char*)&uChar, lpString + 1, 1);
	if (uChar >= 0x81 && uChar <= 0x9F || uChar >= 0xE0 && uChar <= 0xFC);
	{
		uChar = SjisUnicodeTable[uChar];
		unsigned char p = 0;
		memcpy(&p, (unsigned char*)&uChar + 1, 1);
		memcpy((unsigned char*)&uChar + 1, (unsigned char*)&uChar, 1);
		memcpy((unsigned char*)&uChar, &p, 1);
		//return TextOutW(hdc, x, y, (LPWSTR)uChar, c);
	}
	return ((PfuncTextOutA)g_pOldTextOutA)(hdc, x, y, (LPCSTR)&uChar, c);
}
`
For Whirlpool, Because the SJIS encoding, you can't change the codepage of text.
I think you can map chars to SJIS. It can be displayed.
This is an example in Chinese:
![SU~DG3({G4ZH2$01 CFPM(Y](https://user-images.githubusercontent.com/47900658/75736710-e634e780-5d38-11ea-9772-73617ba7d2a8.png)

**Comment by imKota** [comment]
@MZSHproject hello!

> auto fs = fopen("CHS.TBL", "rb");//MAP TABLE. MADE BY YOURSELF

This is exactly the problem.
I tried to do it.. [rus.tbl.zip](https://github.com/MZSHproject/YU-RIS-PATCH/files/4278918/rus.zip)

Do you have discord/skype/telegram ?

**Comment by MZSHproject** [comment]
> @MZSHproject hello!
> 
> > auto fs = fopen("CHS.TBL", "rb");//MAP TABLE. MADE BY YOURSELF
> 
> This is exactly the problem.
> I tried to do it.. [rus.tbl.zip](https://github.com/MZSHproject/YU-RIS-PATCH/files/4278918/rus.zip)
> 
> Do you have discord/skype/telegram ?

[RU.zip](https://github.com/MZSHproject/YU-RIS-PATCH/files/4278984/RU.zip)
telegram: AyamiKaze
